[project]
name = "heat-eq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    'jupyter',
    'matplotlib',
    "sympy>=1.14.0",
]
